<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_StateValve_Process_Source" Id="{416bcdfe-aa9b-46a2-89d5-9de465f90e80}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_StateValve_Process_Source : bool
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_StateValve_Process_Source:= GVL_IO_VALVE.DO_00_V01ChalcogenCarrierChange = FALSE AND
				GVL_IO_VALVE.DO_00_V02MOCarreirChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V03H2SeSourceChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V04H2SSourceChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V05Source_1TMInCarrierChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V06Source_1TMInBypass = FALSE  AND
				GVL_IO_VALVE.DO_00_V07Source_2TMGaCarrierChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V08Source_2TMGaBypass = FALSE  AND
				GVL_IO_VALVE.DO_00_V09Source_3DMSeCarrierChange = FALSE  AND
				GVL_IO_VALVE.DO_00_V10Source_3DMSeBypass = FALSE  AND
				GVL_IO_VALVE.DO_00_V11Source_4ChalcogenCarrierChange = FALSE  and
				GVL_IO_VALVE.DO_00_V12Source_4ChalcogenBypass = FALSE; ]]></ST>
    </Implementation>
    <LineIds Name="F_StateValve_Process_Source">
      <LineId Id="30" Count="10" />
      <LineId Id="19" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>